baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My blog'

theme = "hugo-blog-awesome"


[[params.socialIcons]]
name = "github"
url = "https://github.com/msdlr"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"
