baseURL = 'https://msdlr.github.io/blog/'
languageCode = 'en-us'
title = 'My blog'

theme = "hugo-blog-awesome"

[menu]
[[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30
[[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20

[[params.socialIcons]]
name = "github"
url = "https://github.com/msdlr"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"
